---
parser: babel-eslint

env:
  browser: true
  jest: true
  node: true

plugins:
  - jest
  - lodash

extends:
  - airbnb
  - plugin:jest/recommended
  - plugin:lodash/recommended

rules:
  no-console: 0
  lodash/import-scope:
    - 2
    - full
  import/no-unresolved:
    - 2
    - ignore:
      - gon
  react/prop-types: 0
  jsx-a11y/label-has-for: 0
